# Generated by Django 5.1.2 on 2024-10-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("NGO", "Non-Governmental Organization"),
                            ("GOV", "Government"),
                            ("PRV", "Private"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
            ],
        ),
    ]
