# Generated by Django 5.1.2 on 2024-10-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_agency_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.JSONField()),
                ("number_of_licenses", models.IntegerField()),
                (
                    "per_license_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "hosting_by",
                    models.CharField(
                        choices=[("cloud", "Cloud"), ("on_premise", "On-premise")],
                        max_length=20,
                    ),
                ),
                ("hosting_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="users.agency",
                    ),
                ),
            ],
        ),
    ]
